
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

four_wheel_steering_controller:
  type: "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ['fl_drive_joint', 'fr_drive_joint']
  rear_wheel: ['rl_drive_joint', 'rr_drive_joint']
  front_steering: ['fl_steer_joint', 'fr_steer_joint']
  rear_steering: ['rl_steer_joint', 'rr_steer_joint']
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.05]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.05]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  track : 0.47
  wheel_radius : 0.13
  wheel_base: 0.64
  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0
  
  # Base frame_id
  base_frame_id: base_link # default: base_link
  enable_odom_tf: false
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2  # m/s
      min_velocity           : -2 # m/s
      has_acceleration_limits: true
      max_acceleration       : 5.0  # m/s^2
      min_acceleration       : -5.0 # m/s^2
  # 重要！！！！！！！！！！！！！！！！！！！！！
  # 这里把angular_z的值当成车轮转角加速度
  angular:  
    z:
      has_velocity_limits    : true
      max_velocity           : 0.39  # rad/s
      min_velocity           : -0.39
      has_acceleration_limits: true
      max_acceleration       : 3.14  # rad/s^2
      min_acceleration       : -3.14

  # /gazebo_ros_control:
  #   pid_gains:
  #     fl_steer_joint:
  #       p: 50
  #       i: 0.0
  #       d: 0.01
  #     fr_steer_joint:
  #       p: 50
  #       i: 0.0
  #       d: 0.01
  #     rl_steer_joint:
  #       p: 50
  #       i: 0.0
  #       d: 0.01
  #     rr_steer_joint:
  #       p: 50
  #       i: 0.0
  #       d: 0.01
  #     fl_drive_joint: 
  #       p: 10.0
  #       i: 0.0
  #       d: 0.0
  #     fr_drive_joint: 
  #       p: 10.0
  #       i: 0.0
  #       d: 0.0
  #     rl_drive_joint: 
  #       p: 10.0
  #       i: 0.0
  #       d: 0.0
  #     rr_drive_joint: 
  #       p: 10.0
  #       i: 0.0
  #       d: 0.0
